/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const LyricLine = IDL.Record({
  'text' : IDL.Text,
  'timeSeconds' : IDL.Float64,
});
export const Song = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'audioUrl' : IDL.Text,
  'artist' : IDL.Text,
  'coverUrl' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getLyrics' : IDL.Func([IDL.Nat], [IDL.Vec(LyricLine)], ['query']),
  'getPlayCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getTopPlayed' : IDL.Func([], [IDL.Vec(Song)], ['query']),
  'getTotalSecondsListened' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'recordPlay' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleFavorite' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const LyricLine = IDL.Record({
    'text' : IDL.Text,
    'timeSeconds' : IDL.Float64,
  });
  const Song = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'audioUrl' : IDL.Text,
    'artist' : IDL.Text,
    'coverUrl' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFavorites' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getLyrics' : IDL.Func([IDL.Nat], [IDL.Vec(LyricLine)], ['query']),
    'getPlayCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getSongs' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getTopPlayed' : IDL.Func([], [IDL.Vec(Song)], ['query']),
    'getTotalSecondsListened' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'recordPlay' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleFavorite' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };